version: '2'
services:
  db:
    image: postgres
    ports:
      - "18342:5432"
    volumes:
      - ./web-data:/var/lib/postgres
  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    environment:
      - DB_USER_POSTGRES_USERNAME=postgres
      - DB_USER_POSTGRES_HOST=db
    depends_on:
      - db
