version: '3'
services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./web-data:/var/lib/postgresql/data
  web:
    image: heyfam:latest
    build: .
    command: ["./wait-for-it.sh", "db:5432", "--", "bash", "-c", "./entrypoint.sh && rm -f tmp/pids/server.pid && bundle exec rails s -e development -p 3000 -b '0.0.0.0'"]
    volumes:
      - .:/root/src/app
    ports:
      - "3000:3000"
    environment:
      - DB_USER_POSTGRES_USERNAME=postgres
      - DB_USER_POSTGRES_HOST=db
      - DB_USER_POSTGRES_PORT=5432
      - RAILS_ENV=development
      - RACK_ENV=development
    depends_on:
      - db
    stdin_open: true
    # tty: true
