const constants = {
  FILTER_BY_ROLE: "FILTER_BY_ROLE",
  FILTER_BY_TYPE: "FILTER_BY_TYPE",
  SEARCH_JOBS: "SEARCH_JOBS",
  SET_ACTIVE_ROLE: "SET_ACTIVE_ROLE",
  SET_ACTIVE_TYPE: "SET_ACTIVE_TYPE",
  SAVE_JOB: "SAVE_JOB",
  UNSAVE_JOB: "UNSAVE_JOB",
  FETCH_JOBS: "FETCH_JOBS",
}
